namespace RectClash.Game
{
    public enum GameEvent
    {
        CREATE_FOOTSOLIDER,
        GRID_CELL_SELECTED,
        GRID_CELL_UNSELECTED,
        GRID_MOVE_CONF,
        GRID_CLEAR_SELECTION,
		UNIT_MOVED,
        ATTACK_TARGET,
		RECEIVE_DAMAGE,
        ATTACK_ATTACKER,
		UNIT_SELECTED,
		UNIT_DIED,
        ATTACK_CONF,
		TRIGGER_TURN_END,
		TURN_END
    }
}